services:
  transactions_db:
    image: mysql
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\gilma\transmysql:/var/lib/mysql
    environment:
      MYSQL_USER: phnx
      MYSQL_PASSWORD: PHNX
      MYSQL_DATABASE: transactions_db
      MYSQL_ROOT_PASSWORD: PHNX
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  transactions:
    image: transactions
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PHNX
      SPRING_DATASOURCE_URL: 'jdbc:mysql://transactions_db:3306/transactions_db'
    depends_on:
      transactions_db:
        condition: service_healthy
