services:
  springdb:
    image: mysql
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\gilma\mysql:/var/lib/mysql
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: SPRINGGO
      MYSQL_DATABASE: springdb
      MYSQL_ROOT_PASSWORD: SPRINGGO
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  light-wall-service:
    image: springapp
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://springdb:3306/springdb'
    depends_on:
      springdb:
        condition: service_healthy
